"""initial schema

Revision ID: c8f123e664c0
Revises: 
Create Date: 2026-05-09 18:37:20.564952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f123e664c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts_log',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fired_ts', sa.Float(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channels', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('capture_sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('started_ts', sa.Float(), nullable=False),
    sa.Column('ended_ts', sa.Float(), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('frames_in', sa.Integer(), nullable=False),
    sa.Column('frames_out', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('metrics_snapshots',
    sa.Column('snapshot_ts', sa.Float(), nullable=False),
    sa.Column('frames_per_min', sa.Float(), nullable=True),
    sa.Column('events_per_hour', sa.Float(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_ts')
    )
    op.create_table('parse_watermarks',
    sa.Column('journal_file', sa.Text(), nullable=False),
    sa.Column('last_offset', sa.Integer(), nullable=False),
    sa.Column('last_line', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('last_run_ts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('journal_file')
    )
    op.create_table('schemas',
    sa.Column('schema_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_tag', sa.Text(), nullable=True),
    sa.Column('competition_type', sa.Text(), nullable=True),
    sa.Column('competition_subtype', sa.Text(), nullable=True),
    sa.Column('countdown_s', sa.Integer(), nullable=True),
    sa.Column('market_template_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Text(), nullable=True),
    sa.Column('content_library', sa.Text(), nullable=True),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.Column('is_two_legs_group', sa.Boolean(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('first_seen_ts', sa.Float(), nullable=False),
    sa.Column('last_seen_ts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_table('schema_markets',
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Text(), nullable=False),
    sa.Column('market_name', sa.Text(), nullable=False),
    sa.Column('odd_id', sa.Text(), nullable=False),
    sa.Column('odd_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.schema_id'], ),
    sa.PrimaryKeyConstraint('schema_id', 'slot')
    )
    op.create_table('schema_participants',
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('fifa_code', sa.Text(), nullable=True),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.schema_id'], ),
    sa.PrimaryKeyConstraint('schema_id', 'team_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('season_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.Column('matchdays_completed', sa.Integer(), nullable=False),
    sa.Column('champion_team_id', sa.Text(), nullable=True),
    sa.Column('runner_up_team_id', sa.Text(), nullable=True),
    sa.Column('raw_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.schema_id'], ),
    sa.PrimaryKeyConstraint('season_id'),
    sa.UniqueConstraint('schema_id', 'season_index', name='uq_seasons_schema_index')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index('idx_seasons_schema', ['schema_id'], unique=False)

    op.create_table('events',
    sa.Column('e_block_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('server_status', sa.Text(), nullable=True),
    sa.Column('event_time', sa.Text(), nullable=True),
    sa.Column('captured_ts', sa.Float(), nullable=False),
    sa.Column('settled_ts', sa.Float(), nullable=True),
    sa.Column('home_team_id', sa.Text(), nullable=True),
    sa.Column('away_team_id', sa.Text(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('match_day', sa.Integer(), nullable=True),
    sa.Column('leg_order', sa.Integer(), nullable=True),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('champ_id', sa.Integer(), nullable=True),
    sa.Column('num_runners', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Text(), nullable=True),
    sa.Column('second_id', sa.Text(), nullable=True),
    sa.Column('third_id', sa.Text(), nullable=True),
    sa.Column('final_order', sa.Text(), nullable=True),
    sa.Column('track_condition', sa.Float(), nullable=True),
    sa.Column('weather', sa.Text(), nullable=True),
    sa.Column('surface', sa.Text(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('won_markets', sa.Text(), nullable=True),
    sa.Column('won_market_count', sa.Integer(), nullable=True),
    sa.Column('content_duration', sa.Float(), nullable=True),
    sa.Column('media_id', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('raw_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.schema_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('e_block_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_product', ['product'], unique=False)
        batch_op.create_index('idx_events_schema_time', ['schema_id', 'event_time'], unique=False)
        batch_op.create_index('idx_events_season_md', ['season_id', 'match_day'], unique=False)
        batch_op.create_index('idx_events_settled_ts', ['settled_ts'], unique=False)
        batch_op.create_index('idx_events_status', ['server_status'], unique=False)

    op.create_table('match_day_snapshots',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('match_day', sa.Integer(), nullable=False),
    sa.Column('finalized_ts', sa.Float(), nullable=True),
    sa.Column('matches_json', sa.JSON(), nullable=False),
    sa.Column('standings_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('season_id', 'match_day')
    )
    op.create_table('event_participants_football',
    sa.Column('e_block_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['e_block_id'], ['events.e_block_id'], ),
    sa.PrimaryKeyConstraint('e_block_id', 'side')
    )
    op.create_table('event_runners',
    sa.Column('e_block_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Text(), nullable=False),
    sa.Column('trap', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prob', sa.Float(), nullable=True),
    sa.Column('form', sa.Float(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('ability', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('stamina', sa.Float(), nullable=True),
    sa.Column('wins', sa.Float(), nullable=True),
    sa.Column('place', sa.Float(), nullable=True),
    sa.Column('pace', sa.Text(), nullable=True),
    sa.Column('forecast', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['e_block_id'], ['events.e_block_id'], ),
    sa.PrimaryKeyConstraint('e_block_id', 'runner_id')
    )
    op.create_table('odds',
    sa.Column('e_block_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['e_block_id'], ['events.e_block_id'], ),
    sa.PrimaryKeyConstraint('e_block_id', 'slot')
    )
    op.create_table('odds_history',
    sa.Column('e_block_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('snapshot_ts', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['e_block_id'], ['events.e_block_id'], ),
    sa.PrimaryKeyConstraint('e_block_id', 'slot', 'snapshot_ts')
    )
    op.create_table('standings',
    sa.Column('e_block_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('match_day', sa.Integer(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goal_diff', sa.Integer(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['e_block_id'], ['events.e_block_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('e_block_id', 'team_id')
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index('idx_standings_season_md', ['season_id', 'match_day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index('idx_standings_season_md')

    op.drop_table('standings')
    op.drop_table('odds_history')
    op.drop_table('odds')
    op.drop_table('event_runners')
    op.drop_table('event_participants_football')
    op.drop_table('match_day_snapshots')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_status')
        batch_op.drop_index('idx_events_settled_ts')
        batch_op.drop_index('idx_events_season_md')
        batch_op.drop_index('idx_events_schema_time')
        batch_op.drop_index('idx_events_product')

    op.drop_table('events')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index('idx_seasons_schema')

    op.drop_table('seasons')
    op.drop_table('schema_participants')
    op.drop_table('schema_markets')
    op.drop_table('schemas')
    op.drop_table('parse_watermarks')
    op.drop_table('metrics_snapshots')
    op.drop_table('capture_sessions')
    op.drop_table('alerts_log')
    # ### end Alembic commands ###
